### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by TakehiroTsukagoshi** [TakehiroTsukagoshi/chat-space#10]
#  IPアドレス
18.178.23.229

**Comment by yasunamiura** [comment]
塚越さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

- グループ作成画面のビューを整えましょう
[![Image from Gyazo](https://i.gyazo.com/cdb59e097477fb8e5084e42c79e17ef9.png)](https://gyazo.com/cdb59e097477fb8e5084e42c79e17ef9)
見本
[![Image from Gyazo](https://i.gyazo.com/3898acb41fdf4538f88946c3024984ab.png)](https://gyazo.com/3898acb41fdf4538f88946c3024984ab)


修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
